version: 2

updates:
  - package-ecosystem: pip
    directory: '/'
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"] # ignore patch updates
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: '/'
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"] # ignore patch updates
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"] # ignore patch updates
    open-pull-requests-limit: 5

  - package-ecosystem: terraform
    directory: '/'
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"] # ignore patch updates
    open-pull-requests-limit: 5
