---
version: '3.8'

services:
  velo-action:
    container_name: velo-action
    build:
      context: .
      dockerfile: Dockerfile
    env_file: env.dev-vars
    volumes:
      - ../velo-action:/github/workspace:ro
      # - ${INPUT_WORKSPACE}:/github/workspace:ro
      # - ${CLOUDSDK_CONFIG}:/root/.config/gcloud:ro
    working_dir: /github/workspace
