---
version: '3.8'

services:
  velo-action:
    container_name: velo-action
    build:
      context: .
      dockerfile: Dockerfile
    env_file: env.dev-vars
    environment:
      INPUT_VERSION: '0.0.1'
      INPUT_WORKSPACE: ./velo-action
      INPUT_PROJECT: velo-action
      INPUT_LOG_LEVEL: DEBUG
      INPUT_VELO_PROJECT: nube-velo-dev
      GOOGLE_APPLICATION_CREDENTIALS: /root/.config/gcloud/application_default_credentials.json
    volumes:
      - $PWD:/github/workspace/velo-action:ro
      - $HOME/.config/gcloud/application_default_credentials.json:/root/.config/gcloud/application_default_credentials.json:ro
    working_dir: /github/workspace/
