---
version: '3.8'

services:
  velo-action:
    container_name: velo-action
    build:
      context: .
      dockerfile: Dockerfile
    image: act-github-actions-velo:latest
    env_file: .env
    environment: {}
    volumes:
      - ${PWD}:/github/workspace
    working_dir: /github/workspace
