[tool.poetry]
name = "velo-action"
version = "0.1.0"
description = "Github Action used to generate velo deploy version and trigger a release."
authors = ["Anders Liland <anders.liland@oda.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
semantic-version = "^2.8"
gitversion = "^2.1"
appdirs = "^1.4"
google = "^3.0"
google-auth = "^1.34"
google-cloud-storage = "^1.42"
google-cloud-secret-manager = "^2.5"
pydantic = "^1.8.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
black = "^21.5b2"
flake8 = "^3.8"
flake8-bugbear = "^21.4"
mypy = "^0.910"
pylint = "^2.9"
pytest-mock = "^3.6"
docker-image-size-limit = "^0.4.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
target-version = ['py39']
safe = true
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.venv
  | _build
  | build
  | dist
  | migrations
)/
'''
