---
name: Gitversion
description: |
  Generate a GitVersion and reformat it to multiple formats.
outputs:
  version:
    description: |
      Gitversion generated based on commit history
    value: ${{ steps.gitversion.outputs.version }}
  merged-version:
    description: |
      SemVer after merge to main. Only x.y.z without branch name and commit numbers.
    value: ${{ steps.gitversion.outputs.merged-version }}
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # required for gitversion

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.11
      with:
        versionSpec: "5.x" # What version of Gitversion to use

    - name: Generate gitversion
      shell: bash
      id: gitversion
      run: |
        set -x
        echo "::set-output name=version::$(dotnet-gitversion /showvariable SemVer)"
        echo "::set-output name=merged-version::$(dotnet-gitversion /showvariable SemVer | sed 's/[[:alpha:]|(|[:space:]]//g' | awk -F- '{print $1}')"

    - name: Print versions
      run: |
        set -x
        echo "Version is ${{ steps.gitversion.outputs.version }}"
        echo "Merged version is ${{ steps.gitversion.outputs.merged-version }}"
      shell: bash
