---
name: Docs-to-centro
description: |
  Upload /docs folder to Centro
inputs:
  entity:
    description: |
      The Centro entity
    required: true
    default: Component
  name:
    description: |
      Gitversion generated based on commit history
    required: true
  namespace:
    description: |
      Centro namespace
    required: false
    default: default
  techdocs_version:
    description: |
      Version of the techdocs/cli NPM package
    required: false
    default: 0.8.6
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install techdocs-cli
      shell: bash
      run: npm install -g @techdocs/cli@${{ inputs.techdocs_version }}

    - name: Setup python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.2

    - name: Install Mkdocs
      shell: bash
      run: |
        pip install mkdocs-techdocs-core==1.0.0

    # Usefull to run as a debugging tool.
    # The techdocs cli does not propagate the mkdocs erros in a good way.
    - name: Mkdocs build
      shell: bash
      run: |
        mkdocs build --verbose

    - name: Generate docs
      shell: bash
      run: |
        techdocs-cli generate --no-docker --verbose --source-dir . --output-dir ./site/

    # When on a branch with name 'docs/**' upload to Centro staging.
    # This is allowd to fail since staging can be down.
    - name: Authenticate to nube-centro-staging
      uses: google-github-actions/setup-gcloud@v0.6.0
      if: github.ref != 'refs/heads/main'
      with:
        service_account_key: ${{ secrets.CENTRO_DOCS_UPLOADER_GSA_KEY_STAGING }}
        project_id: nube-centro-staging
        export_default_credentials: true

    - name: Publish docs to Centro staging (on every branch except main)
      if: github.ref != 'refs/heads/main'
      shell: bash
      run: |
        techdocs-cli publish --publisher-type googleGcs \
          --storage-name centro-docs-staging \
          --entity "${{ inputs.namespace }}/${{ inputs.entity }}/${{ inputs.name }}"

    - name: Authenticate to nube-centro-prod
      uses: google-github-actions/setup-gcloud@v0.6.0
      if: github.ref == 'refs/heads/main'
      with:
        service_account_key: ${{ secrets.CENTRO_DOCS_UPLOADER_GSA_KEY_PROD }}
        project_id: nube-centro-prod
        export_default_credentials: true

    - name: Publish docs to Centro prod (only from main branch)
      if: github.ref == 'refs/heads/main'
      shell: bash
      run: |
        techdocs-cli publish --publisher-type googleGcs \
          --storage-name centro-docs-prod \
          --entity "${{ inputs.namespace }}/${{ inputs.entity }}/${{ inputs.name }}"
