---
name: '[lint] markdown'

on:
  push:
    paths:
      - '.github/workflows/lint-markdown.yml'
      - '.markdownlint.yaml'
      - '**.md'

jobs:
  markdownlint:
    name: markdownlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: markdownlint
        uses: nosborn/github-action-markdown-cli@v3.0.1
        with:
          files: .
          config_file: ".markdownlint.yaml"
