---
name: '[lint] pre-commit'

on:
  push:

jobs:
  pre_commit:
    name: pre-commit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        id:
          - trailing-whitespace
          - check-added-large-files
          - check-case-conflict
          - check-symlinks
          - detect-private-key
          - end-of-file-fixer
          - sort-simple-yaml
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v3

      - uses: pre-commit/action@v2.0.3
        name: ${{ matrix.id }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          extra_args: ${{ matrix.id }}
