name: Test Velo-action on main branch
on:
  push:
    # branches:
    #   - "main"

env:
  IMAGE: eu.gcr.io/nube-hub/velo-action

jobs:
  test_velo_action_main:
    runs-on: ubuntu-latest
    name: Test Velo-action in main branch
    steps:
      - uses: actions/checkout@v2

      - name: Velo Version
        id: velo_version
        uses: kolonialno/velo-action@velo-action
        with:
          mode: VERSION

      - run: |
          docker build -t eu.gcr.io/nube-hub/velo-action:${{ steps.velo_version.outputs.version }} .
          docker tag eu.gcr.io/nube-hub/velo-action:${{ steps.velo_version.outputs.version }} ${{ env.IMAGE }}:latest

      - name: Wait on CI
        uses: lewagon/wait-on-check-action@v0.2
        if: ${{ !env.ACT }}  # Do not run when testing locally using act
        with:
          ref: ${{ github.ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          running-workflow-name: test_velo_action_main
          check-name: CI done

      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.NUBE_HUB_GCR_KEY }}
          project_id: nube-hub
          export_default_credentials: true

      - run: gcloud auth configure-docker -q

      - run: |
          docker push ${{ env.IMAGE }}:${{ steps.velo_version.outputs.version }}
          docker push ${{ env.IMAGE }}:latest

      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.VELO_CI_KEY_PROD }}
          project_id: nube-velo-prod
          export_default_credentials: true

      - name: Velo Deploy
        id: velo_deploy
        uses: kolonialno/velo-action@velo-action
        with:
          mode: DEPLOY
          octopus_cli_server: ${{ secrets.VELO_CI_OCTOPUS_URL }}
          octopus_cli_api_key: ${{ secrets.VELO_CI_OCTOPUS_API_KEY }}
          service_account_key: ${{ secrets.VELO_CI_KEY_PROD }}
          velo_artifacts_bucket_name: ${{ secrets.VELO_ARTIFACTS_BUCKET_NAME_PROD }}
