name: Test Velo-action locally
on:
  push:
    branches-ignore:
      - main

env:
  IMAGE: eu.gcr.io/nube-hub/velo-action

jobs:
  test_action_in_repo:
    runs-on: ubuntu-18.04
    name: Test Velo action using local file
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # all history for all branches and tags.

      - uses: google-github-actions/setup-gcloud@v0.2.0
        if: ${{ !env.ACT }}  # Do not wait then testing locally using act
        with:
          service_account_key: ${{ secrets.VELO_CI_KEY_PROD }}
          project_id: nube-velo-prod
          export_default_credentials: true

      - name: Velo Version
        id: velo_version
        uses: ./
        with:
          mode: VERSION

      - run: gcloud auth configure-docker -q

      - run: |
          docker build -t ${{ env.IMAGE }}:${{ steps.velo_version.outputs.version }} .
          docker tag ${{ env.IMAGE }}:${{ steps.velo_version.outputs.version }} ${{ env.IMAGE }}:latest

      - name: Wait on CI
        uses: lewagon/wait-on-check-action@v0.2
        if: ${{ !env.ACT }}  # Do not wait then testing locally using act
        with:
          ref: ${{ github.ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          running-workflow-name: test_action_in_repo
          check-name: CI done

      - run: |
          docker push ${{ env.IMAGE }}:${{ steps.velo_version.outputs.version }}
          docker push ${{ env.IMAGE }}:latest

      - name: Velo Deploy
        id: velo_deploy
        uses: ./
        with:
          mode: DEPLOY
          octopus_cli_server: ${{ secrets.VELO_CI_OCTOPUS_URL }}
          octopus_cli_api_key: ${{ secrets.VELO_CI_OCTOPUS_API_KEY }}
          service_account_key: ${{ secrets.VELO_CI_KEY_PROD }}
          velo_artifacts_bucket_name: ${{ secrets.VELO_ARTIFACTS_BUCKET_NAME_PROD }}
